name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches: "main"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_topics: yes
          
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Terminal template
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes

      - name: Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_habits: yes
          plugins_errors_fatal: yes

      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_languages: yes
          plugins_errors_fatal: yes

      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes

      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Traffic plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes


      - name: Isocalendar plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes

      - name: Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes

      - name: Gists plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes

      - name: Projects plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: yes
