name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches: "main"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: napolitain/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: "html,css,xaml,postscript,netlogo,pug"
          plugin_languages_skipped: "napolitain.github.io,metrics"
          plugin_languages_details: percentage             # Additionally display total bytes size and percentage
          repositories_affiliations: "collaborator"

